species: data/LFS-phylogenomics-taxon-selection.csv

# settings realted to busco
busco:
    set: "ascomycota_odb9"
    threads: 8
    augustus_species: anidulans
    additional_parameters: ""

# Here different filtering options can be set for the busco sequence files:
# dupseq: how occasionally found duplicated sequences should be handled: persample = for each busco filter out the samples with duplicated sequences. perfile = filter out complete busco sequence file.
# cutoff: minimum proportion of busco completeness a species needs so that it is included in the analysis.
# minsp: minimum number of species for which a busco was found so that it is included in the analysis.
filtering:
    dupseq: "persample"
    cutoff: 0.5
    minsp: 3
    seq_type: "aa"
# settings related to alignment and trimming
alignment:
    method: mafft
    threads: 8
    parameters: --quiet --auto
extract_sequences:
    cutoff: 0.5
    minsp: 3
# possible trimming options: trimal, aliscore
trimming: 
    method: trimal 
    parameters: -gappyout

# settings related to phylogenetic inference
# phylogenetic method options include iqtree, raxmlng for a concatenated (supermatrix) reconstruction  and astral for species tree reconstruction

tree:
    method: "iqtree"

speciestree:
    method: "astral"

# specific settings for individual tree reconstruction methods
iqtree:
    threads: 16 #specifies the maximum number of threads for -ntmax. The real number will be determined with -nt AUTO internally.
    bootstrap: 1000
    model: MFP
    additional_params: ""
    maxmem: "" #this flag limits ram usage for iqtree: eg. 64G, default (empty quotes is all available mem)
raxmlng:
    threads: 16
    bootstrap: 1000
    additional_params: ""
phylobayes:
    threads: 30
    model: ""
    ngens: 100
    additional_params: "-f"
    nchains: 4

# setting realted to the analysis report
report:
    width: 80
    height: 10
